### ISSUE TITLE
Please add a fixed hosts resolution function

### ISSUE THREAD

**Issue by f4nff** [AdguardTeam/dnsproxy#105]
`dnsproxy -l 127.0.0.1 -p 53 -u  https://doh.360.cn/dns-query?ip=180.163.249.75  -u  https://doh.360.cn/dns-query?ip=101.198.191.4`

If I want to fix the ip of the domain name, then I have to set the hosts, but if a domain name corresponds to multiple ips, modifying the hosts cannot be achieved.
If the current dns is invalid, the domain name is set and the ip corresponding to the hosts is not set, then the doh connection cannot be made, unless the domain name https://1.1.1.1/ is used.

**Comment by ameshkov** [comment]
In this case you should use DNS stamps instead of URLs.

This way you can define the IP address that needs to be used.

For instance, here's how a stamp of `doh.360.cn` with IP `180.163.249.75 ` looks like:
`sdns://AgMAAAAAAAAADjE4MC4xNjMuMjQ5Ljc1AApkb2guMzYwLmNuCi9kbnMtcXVlcnk`

You can examine it and make other stamps here:
https://dnscrypt.info/stamps/
