### ISSUE TITLE
dnsproxy v0.43.0 - DoQ SERVFAIL

### ISSUE THREAD

**Issue by pengelana** [AdguardTeam/dnsproxy#240]
Start from dnsproxy v0.43.0 against [Adguard-Coredns](https://github.com/AdguardTeam/coredns), dns-over-quic always return SERVFAIL.

**Comment by Lanius-collaris** [comment]
If it's ID mismatch error, please try v0.43.1

**Comment by pengelana** [comment]
Same error with v0.43.1

**Comment by ameshkov** [comment]
That's natural, CoreDNS implements a rather old draft of DoQ, dnsproxy implements the RFC and they're not compatible.

I'd say you should use `dnsproxy` itself instead of CoreDNS to add DoQ support.

We don't use CoreDNS for AdGuard DNS anymore and we're going to publish the new code rather soon, but I am not sure if it fits your needs.
