### ISSUE TITLE
Unable to set cache min TTL via config file

### ISSUE THREAD

**Issue by jcoetzee** [AdguardTeam/dnsproxy#258]
I'm unsure of the syntax for specifying cache min TTL in the config file. The argument works when specified on the command line but when I try either `cache_ttl_min` or `cache_min_ttl` in the config file it has no effect. What is the correct syntax for this? Is there documentation on the syntax for the config file?

Example config file:
```
upstream:
  - quic://...
bootstrap:
  - "1.1.1.1:53"
cache: true
cache_ttl_min: 2700
cache_optimistic: true

```

As an aside, it would be helpful if the config parser warned when processing entries it doesn't know about. Additionally running in verbose mode should output all the configured config options so it's clear if an item has been configured as expected (i.e. how can I confirm that cache optimistic has been set correctly?)

**Comment by iJorgen** [comment]
> What is the correct syntax for this?

Try entering it with "-" instead of "_"

`cache-min-ttl: 2700`
`cache-optimistic: true`

> How can I confirm that cache optimistic has been set correctly?

I tested my setup with Wireshark or a DNS query sniffer to confirm that stale records is returned with a TTL=10. That short TTL means Optimistic cache is active and it was picked from the cache while being refreshed upstream in the background.

> It would be helpful if the config parser warned when processing entries it doesn't know about.

If you run it manually from CLI with your config-file, it shows a bunch of info like caching enabled, min-ttl, max-ttl etc. to confirm it has understood the syntax.

**Comment by ameshkov** [comment]
As I understand, it was sorted out?
