### ISSUE TITLE
 "Can the -l command listen for domain-based encrypted connections?"

### ISSUE THREAD

**Issue by Muyv-shanren** [AdguardTeam/dnsproxy#369]
Hello, I would like to inquire whether the ./dnsproxy -l command can be used to listen for domain-based encrypted connections. Specifically, I am configuring encrypted DNS with a domain like https://mydns.com/dns-query. My intention is to establish a connection between me and dnsproxy for this encrypted connection. dnsproxy will then forward the requests to the upstream server at tls://8.8.4.4. Currently, I have successfully configured the upstream server, and it works fine using an unencrypted IP on port 53.

However, when I configure the listener -l with the domain, I encounter errors. If I use an IP, it prompts a certificate error, and if I use a domain, it indicates that it cannot listen, resulting in a listening error.

The above question, I have searched on 'Question', Google, and ChatGPT.

**Comment by ameshkov** [comment]
Hi, in order to accept encrypted connections you need to supply a valid certificate&key to dnsproxy:
https://github.com/AdguardTeam/dnsproxy?tab=readme-ov-file#encrypted-dns-server 

To do this you'll need the following:
1. A server with a public static IP address (this one you'll need to use in the `-l` argument)
2. A valid TLS certificate for your domain name (you can get one for free with letsencrypt or zerossl)
3. The certificate's private key.
