### ISSUE TITLE
Adguard Home not showing real client ip when run as Upstream.

### ISSUE THREAD

**Issue by 7gxycn08** [AdguardTeam/dnsproxy#374]
I'm running dnsproxy dnscrypt locally and accessing it locally however real client ip won't show in Adguard Home Query Logs.
--edns                       Use EDNS Client Subnet extension
--edns-addr=                 Send EDNS Client Address

tried adding those parameters but still it won't show in the logs.

**Comment by EugeneOne1** [comment]
@7gxycn08, hello.  Please consider using the _Discussions_ section of the [AdGuard Home](https://github.com/AdguardTeam/AdGuardHome) repo.  It would also be wonderful if you describe the whole setup and environment of AdGuard Home so that we understand the issue better.  We'll close this for now, if you don't mind.
