### ISSUE TITLE
upstream doh validate is wrong

### ISSUE THREAD

**Issue by sanyo0714** [AdguardTeam/dnsproxy#411]
2024/08/13 20:10:52 [fatal] Cannot create an upstream: invalid address xxx_xxx.xxxx.com: bad hostname "xxx_xxx.xxxx.com": bad hostname label "xxx_xxx": bad hostname label rune '_'

domain name also need follow https://datatracker.ietf.org/doc/html/rfc2181#autoid-30

**Comment by EugeneOne1** [comment]
Hello, @sanyo0714.  This change might actually make sense since we already allow so-called "domain names" (as opposed to "hostnames") to be used within upstream domain specifications.  Perhaps using the same validation rules for upstream names and their domain specifications would make the API more consistent and predictable.

@ameshkov, what do you think?  Just in case, see https://github.com/AdguardTeam/golibs/issues/9#issuecomment-2288313654.
